### ISSUE TITLE
Unable to handle commas

### ISSUE THREAD

**Issue by kvnixh** [yiannakasgeorge/TwittyJar#7] opened 2020-03-04 05:14 UTC
Hi,
Thanks for developing this application which is really helpful. But I've observed that, tweets having commas don't download completely. The tweet gets cut off at the comma and also, the rest of the features like Number of retweets, Tweet type and poster followers count don't get reported for the tweets having a comma.
Kidnly let me know how to sort this issue

**Comment by yiannakasgeorge** [comment] 2020-03-15 07:10
Hey ! Thanks for your kind words. I have tried to replicate this issue and it seems that TwittyJar actually exports the results containing commas without any issues.

The issue is produced when transferring the data into Excel.

Instead of opening the CSV directly into Excel try the following:
a) Open a blank workbook in Excel.
b) Navigate to the "Data" tab
c) Select the "From Text" Option 
d) Select the CSV file exported
e) Keep the default options in step 1 (Delimited, Start import at row 1, Unicode (UTF-8) as file origin
f) Make sure to select "Tab" in the Delimiters column in step 2 
g) Select "General" in Column data form in step 3
h) Select the existing sheet when prompted to select "Where do you want to put the data"

 That's it. You will notice that tweets with comma (,) are no longer being truncated.

*Using this method, will convert the "Poster username" context to formulas. Select the "Poster username" column and its contents and click "Text to columns" option from the "Data" tab. Choose 'delimited' in step 1, "Tab" in step 2 and "Text" in step 3 to convert them to text. Then just clear the "=" sign from the context.

*For the "Tweet id" column , just form the cells to "Number" with zero decimal places.

Let me know if everything works fine now!

**Comment by yiannakasgeorge** [comment] 2020-03-15 07:17
Updated https://github.com/yiannakasgeorge/TwittyJar/blob/master/README.md documentation with the new method of importing into Excel.

**Closed by yiannakasgeorge** 2020-03-15 07:17 UTC
Labels: documentation
